# Generated by Django 2.2 on 2019-04-18 00:58

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Topic')),
                ('user', models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('desc', models.CharField(blank=True, max_length=1024, verbose_name='Desc')),
                ('priority', models.PositiveIntegerField(choices=[(1, 'Critical'), (2, 'Important'), (3, 'Normal'), (4, 'Low')], default=2, verbose_name='Level')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Done'), (2, 'Waiting'), (3, 'Doing')], default=3, verbose_name='Status')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create')),
                ('expect_time', models.DateTimeField(blank=True, null=True)),
                ('finished_time', models.DateTimeField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=False, related_name='topic_tasks', to='tasks.Topic', verbose_name='Topic')),
                ('user', models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
